[package]
name = "enum-repr-convert"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
heck = "0.5.0"
proc-macro2 = "1.0.89"
quote = "1.0.37"
syn = "2.0.85"
trybuild = "1.0.101"
